# Generated by Django 3.0.5 on 2020-08-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=500,
                        unique=True,
                        verbose_name='Category title',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        blank=True,
                        max_length=500,
                        unique=True,
                        verbose_name='Category slug',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=500, unique=True, verbose_name='Genre title'
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        blank=True,
                        max_length=500,
                        unique=True,
                        verbose_name='Genre slug',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ('-name',),
            },
        ),
    ]
