# Generated by Django 3.0.5 on 2020-08-25 21:20

import artworks.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('artworks', '0002_auto_20200825_2029')]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=500, verbose_name='Title'),
                ),
                (
                    'year',
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1984),
                            artworks.models.max_value_current_year,
                        ],
                        verbose_name='Year',
                    ),
                ),
                (
                    'rating',
                    models.PositiveIntegerField(
                        choices=[
                            ('1', 1),
                            ('2', 2),
                            ('3', 3),
                            ('4', 4),
                            ('5', 5),
                            ('6', 6),
                            ('7', 7),
                            ('8', 8),
                            ('9', 9),
                            ('10', 10),
                        ],
                        verbose_name='Artwork rating',
                    ),
                ),
                ('description', models.TextField(verbose_name='Description')),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='titles',
                        to='artworks.Category',
                    ),
                ),
                (
                    'genre',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='titles',
                        to='artworks.Genre',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ('-name',),
            },
        )
    ]
