# Generated by Django 3.0.5 on 2020-08-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('artworks', '0003_title')]

    operations = [
        migrations.RemoveField(model_name='title', name='genre'),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(
                related_name='titles', to='artworks.Genre'
            ),
        ),
    ]
