# Generated by Django 3.0.5 on 2020-08-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('artworks', '0006_auto_20200825_2210')]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                max_length=500, unique=True, verbose_name='Category slug'
            ),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(
                max_length=500, unique=True, verbose_name='Genre slug'
            ),
        ),
    ]
