# Generated by Django 3.0.5 on 2020-08-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('artworks', '0007_auto_20200825_2329')]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='titles',
                to='artworks.Category',
                verbose_name='Category',
            ),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(
                related_name='titles',
                to='artworks.Genre',
                verbose_name='Genres',
            ),
        ),
    ]
