# Generated by Django 3.0.5 on 2020-08-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('artworks', '0008_auto_20200826_0747')]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(
                blank=True, null=True, verbose_name='Description'
            ),
        )
    ]
