# Generated by Django 3.0.5 on 2020-08-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('artworks', '0009_auto_20200826_0812')]

    operations = [migrations.RemoveField(model_name='title', name='rating')]
